from enum import Enum


class ClauseType(str, Enum):
    ROLES = "ROLES"
    SUBJECT_DURATION = "SUBJECT_DURATION"
    PURPOSE_NATURE = "PURPOSE_NATURE"
    DATA_CATEGORIES_SUBJECTS = "DATA_CATEGORIES_SUBJECTS"
    SECURITY_TOMS = "SECURITY_TOMS"
    SUBPROCESSORS = "SUBPROCESSORS"
    TRANSFERS = "TRANSFERS"
    BREACH_NOTIFICATION = "BREACH_NOTIFICATION"
    DSAR_ASSISTANCE = "DSAR_ASSISTANCE"
    DELETION_RETURN = "DELETION_RETURN"
    AUDIT_RIGHTS = "AUDIT_RIGHTS"
    CONFIDENTIALITY = "CONFIDENTIALITY"
    LIABILITY = "LIABILITY"
    GOVERNING_LAW = "GOVERNING_LAW"
    ORDER_OF_PRECEDENCE = "ORDER_OF_PRECEDENCE"
